repos:
  # pre-commit hooks
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        exclude: ^.*\b(migrationns)\b.*$
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        exclude: ^.*\b(migrationns)\b.*$
        language_version: python3.10
        args: [--line-length=120]
        stages: [commit]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^.*\b(migrationns)\b.*$
        stages: [commit]